stages:
  - build
  - test
  - deploy

build app:
  stage: build
  image: node:18-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build

deploy review:
  stage: deploy
  image: alpine
  script:
    - echo "Deploying to review"

e2e tests:
  stage: test
  image: cypress/base:16.18.1
  script:
    - npm ci
    - npm install -g serve
    - npm install -g wait-on
    - serve -l 8080 -s dist &
    - wait-on http://localhost:8080
    - npm run e2e
  artifacts:
    when: always
    paths:
      - test-results.xml
    reports:
      junit: test-results.xml
